apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonar-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonar-flask
    spec:
      containers:
      - name: sonar-flask
        image: vishalarao/training_hub1:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5151
