apiVersion: v1
kind: Service
metadata:
  name: sonar-flask
  labels:
    app: sonar-flask
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5151
  selector:
    app: sonar-flask
    
